export const FETCH_ARTICLES_BEGIN = '@saga/FETCH_ARTICLES_BEGIN';
export const FETCH_ARTICLES_SUCCESS = '@saga/FETCH_ARTICLES_SUCCESS';
export const FETCH_ARTICLES_FAILURE = '@saga/FETCH_ARTICLES_FAILURE';
